# Site settings
title: heyo
email: melissaran707@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  my stuff.
baseurl:  # the subpath of your site, e.g. /blog/
url:  # the base hostname & protocol for your site
twitter_username:
github_username:

# Build settings
markdown: kramdown

highlighter: rouge

#Pagination
#paginate: 15
#paginate_path: "/blog/page:num/"


collections:
  portfolio:
    output: true
#    permalink: /portfolio/:path/

  #poetry:
  #  output: true
  #  permalink: /poetry/:path/
